name: Test

on:
  pull_request:
    branches: [ main, master ] # Only trigger on PRs targeting main or master

env:
  STRICT_TESTING: false # Toggle this to true/false to control test failure behavior
  skip_tests: true # Add this line to skip tests entirely

jobs:
  test:
    # Skip the entire job if skip_tests is true
    if: ${{ !env.skip_tests }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm run test
      continue-on-error: true # Tests will run but failures won't fail the workflow
